### ISSUE TITLE
Why  "http://localhost:8080" ？

### ISSUE THREAD

**Issue by webkonglong** [dfinity/rosetta-client#12]
`// A Session is a subclass of RosettaClient, and you can use methods of
// RosettaClient to invoke the Rosetta API.
//
// Session 是 RosettaClient 的子类，可以调用 RosettaClient 的方法使用 Rosetta
// API。
const session = new Session({ baseUrl: "http://localhost:8080" });`
为什么是 "http://localhost:8080" ？
Why  "http://localhost:8080" ？ 
我用"http://localhost:8080"出现了错误
I use it  "http://localhost:8080" an error occurred。

`POST http://localhost:8080/network/list net::ERR_CONNECTION_REFUSED
Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:84)
`

**Comment by TerrorJack** [comment]
使用前需要启动 `ic-rosetta-api` 并同步测试网的所有区块。`8080` 是约定俗成的 `ic-rosetta-api` 监听端口。使用 `docker` 运行 `ic-rosetta-api` 的命令：`docker run -it --rm -p 8080:8080`，等 `You are all caught up to block xxx` 的消息出现后，同步即完成。

**Comment by webkonglong** [comment]
> 使用前需要启动`ic-rosetta-api`并同步测试网的所有区块链。`8080`是约定俗成的`ic-rosetta-api`监听端口。使用`docker`运行`ic-rosetta-api`的命令：`docker run -it --rm -p 8080:8080`，等`You are all caught up to block xxx`的消息出现后，同步即完成。

咨询一下，有文档没，我对这块完全懵逼，我搜索不到 ic-rosetta-api这个文档，可以的画，麻烦帮我贴一个文档地址，另外咨询是否有开发者微信群之类的，

**Comment by TerrorJack** [comment]
这个库的目标用户是加密货币交易所，用于测试和 Dfinity 的 Rosetta API 实现的交互。介意说下您是哪个交易所的吗？

**Comment by webkonglong** [comment]
> 这个库的目标用户是加密货币交易所，用于测试和Dfinity的Rosetta API实现的交互。介意说下您是该交易所的吗？

哦，我想了解一些 @dfinity/rosetta-client 的api文档，或关于 Dfinity和web前端交互的一些文档，不知道可以添加你微信不，或者是否有Dfinity发开的相关微信群，添加，拉我，下？

**Comment by uney** [comment]
一般用戶如何弄錢包？
