### ISSUE TITLE
同一个public_key生成的地址和golang SDK的不一样

### ISSUE THREAD

**Issue by DreamHackchosenone** [dfinity/rosetta-client#38]
我测试用的pub_key: 041f96fac9f3401f716ac14f54639bc53746a2d4e59d9a094bf4d675ef6c7bd0370d26d17c3f33bd56c0b657869cce3de5673d6ab502f43d67f8076158ab47b3e6
golang生成的地址:
5ead61c99c1081693f5f46aaa10e63eee2ef3e87b30955012584f24c2c14c5b4
js生成的地址:
f46c5e24b8bb4c23d51b247868131c16d36df0454b935300100e456e1ec27b60

**Comment by TerrorJack** [comment]
从公钥生成地址的算法因区块链而异。据我所知，dfinity 没有官方的 golang sdk，你很可能用 coinbase 的 golang sdk 用不知哪里来的算法生成的地址。那个是无效的

**Comment by DreamHackchosenone** [comment]
> 从公钥生成地址的算法因区块链而异。据我所知，dfinity 没有官方的 golang sdk，你很可能用 coinbase 的 golang sdk 用不知哪里来的算法生成的地址。那个是无效的

Golang是官方的，地址是这个https://github.com/dfinity/keysmith

**Comment by daoleno** [comment]
这里为什么会用 ECDSA 的 public key 去编码呢？不是 ed25519 签的吗？

https://github.com/dfinity/keysmith/blob/cf7c6cf276b96708350da66c5238c931a1b25cb0/codec/encode.go#L50-L62
