### ISSUE TITLE
How dfinity/rosetta-api connect to icp mainnet ?

### ISSUE THREAD

**Issue by lfj7282** [dfinity/rosetta-client#41]
hi. everyone i have a question.
i use the  dfinity/rosetta-api  want to connect icp ledger  .
i use the  doc https://sdk.dfinity.org/docs/integration/ledger-quick-start.html .
![image](https://user-images.githubusercontent.com/32068791/119000063-591d9300-b9bd-11eb-8f13-a4e4eaac8221.png)

the doc show that  the cmd will connect to the produce network.
but i can not connect to the mainnet
![image](https://user-images.githubusercontent.com/32068791/119000435-b1549500-b9bd-11eb-91d9-d0e2e5a973fc.png)

what should i do?

**Comment by crcrcr999** [comment]
Same problem,if use param '--mainnet' ,will return http 403

**Comment by jadeydi** [comment]
I think it's a normal log, still got `You are all caught up to block 2145` with above error logs

**Comment by jadeydi** [comment]
Same problem, if use param '--mainnet' ,will get http 403

**Comment by jadeydi** [comment]
I have figured it: https://forum.dfinity.org/t/integrate-icp-to-cryptocurrency-wallet/4661/2
