### ISSUE TITLE
Method combine handles unsigned_transaction.updates exception

### ISSUE THREAD

**Issue by JayYan726** [dfinity/rosetta-client#55]
My unsigned_transaction.updates：
![image](https://user-images.githubusercontent.com/50827566/127110433-3a8b95df-d008-49d8-8ece-9e417845eeaf.png)

file:  construction_combine.js
method:  combine
![image](https://user-images.githubusercontent.com/50827566/127110709-0221fb8e-69ef-42fb-af2b-42446dd73618.png)

Error Info:
![image](https://user-images.githubusercontent.com/50827566/127110501-cf2ed784-5d1b-40d2-a206-f080f7a82f33.png)

**Comment by malingzhao** [comment]
how does this resolve
